[package]
name = "deep_space"
version = "2.4.7"
authors = ["Justin Kilpatrick <justin@althea.net>", "Michał Papierski <michal@papierski.net>"]
repository = "https://github.com/althea-net/deep_space"
description = "A highly portable, batteries included, transaction generation and key management library for Cosmos blockchains"
license = "Apache-2.0"
edition = "2018"

[dependencies]
num256 = "0.3"
sha2 = "0.10"
num-bigint = "0.4"
num-traits = "0.2"
ripemd = "0.1"
bech32 = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
base64 = "0.13"
unicode-normalization = {version = "0.1"}
prost-types = "0.7"
prost = "0.7"
pbkdf2 = {version = "0.11"}
hmac = {version = "0.12"}
rand = {version = "0.8"}
rust_decimal = "1.9"
secp256k1 = { version = "0.20", features = ["recovery"] }
tendermint-proto = "0.21"
tonic = "0.4"
bytes = "1.0"
cosmos-sdk-proto = "0.6.3"
log = "0.4"
tokio = {version = "1.4", features=["time"]}
tiny-keccak = { version = "2.0.2", features = ["keccak"], default-features = false }

[dev-dependencies]
rand = "0.8"
sha3 = "0.10"
env_logger = "0.9"
actix-rt = "2.2"


[features]
